AntiGlitcher:
  enabled: true
  taskeveryseconds: 30
  antiglitchdurationseconds: 60
SignBackup:
  enabled: true
  taskeveryseconds: 300
SignFormat:
- '&7[&aRandomTP&7]'
- '&2Blocks: %distance%'
- '&cPrice: %price%'
- '&a(Click here)'
Inventory:
  Rows: 1
  MenuName: '&aSelect RandomTP Distance'
  Items:
    '0':
      id: '322'
      slot: 0
      name: '&8[&a+&8] &aRandomTP User &8[&a+&8]'
      cost: 0
      distance: 250
      world: world
      cooldown: 60
      permission: randomtp.use.user
      lore:
      - '&6Teleport distance: %distance% blocks'
      - '&6Cost: $%cost%'
      - '&aClick here to use!'
    '1':
      id: '322:1'
      slot: 1
      name: '&8[&a+&8] &6RandomTP &e&lVIP &8[&a+&8]'
      cost: 25
      distance: 500
      world: world
      cooldown: 300
      permission: randomtp.use.vip
      lore:
      - '&6Teleport distance: %distance% blocks'
      - '&6Cost: $%cost%'
      - '&aClick here to use!'
