# Rankup configuration file.
# Created by: Okx
# All rights reserved.

ranks: # Defines ranks and their prices
- A:0
- B:10000
- C:30000
- D:75000
prestige: # Defines prestige ranks and their prices
- P1:100000
- P2:200000
messages:
  noMoneyToRankup: |- # Message to send when player doesn't have enough money to rankup
    &4&lError: &cNot enough money!
    &eYou need $%AMOUNTTOTAL%
  highestRank: '&aGood work! You''re at the highest rank (%RANK%)!' # Sent when the player cannot rankup anymore and prestiging is off
  highestRankToPrestige: '&aYou need to prestige to get to a higher rank!' # Sent when the player cannot rankup but can prestige
  successfullRankupPrivate: '&aYou successfully ranked up to: &d%RANK%' # Sent to the player when the player successfully runs /rankup
  successfullRankupPublic: '&a%PLAYER% &esuccessfully ranked up to: &d%RANK%' # Sent to everyone on the server when someone ranks up (configurable)
  successfullPrestigePrivate: '&aYou successfully prestiged up to: &d%RANK%' # Sent to the player when the player successfully runs /prestige
  successfullPrestigePublic: '&a%PLAYER% &esuccessfully prestiged up to: &d%RANK%' # Sent to everyone on the server when someone prestiges (configurable)
  notInLadder: '&cCould not get group from config; please check the Rankup FAQ if
    you are an administrator.' # Sent to the player when they are not in a group specified in ranks
  listRanks: # Configures how ranks are listed
    default: "&r%OLDRANK% &e\xbb &r%RANK% &efor &r%AMOUNT%"
    complete: "&7%OLDRANK% &8\xbb &7%RANK% &8for &7%AMOUNT%"
    inProgress: "&c%OLDRANK% &e\xbb &c%RANK% &efor &c%AMOUNT% &e(%PERCENTDONE%%)"
    custom: # This section should only be needed for very advanced configurations (this can be used for headers)
      A: "&rA &e\xbb &r%RANK% &efor &r%AMOUNT%"
      options:
        overrideComplete: false
        overrideInProgress: false
        overrideDefault: true
  rankTooLowToPrestige: '&cYou cannot prestige to %RANK%, your rank isn''t high enough' # Sent to a player when they cannot prestige
  noMoneyToPrestige: '&cYou cannot prestige to %RANK%, you need %AMOUNTTOTAL%' # Sent to the player when they don't have enough moolah to prestige
  highestPrestigeGroup: '&aGood work! You are at the highest prestige rank (%RANK%)!' # Sent to the plaer when they attempt to prestige but cannot
  noPrestigeRank: none # Placeholder for when a player hasn't prestiged
  publicMessage: true # Should we send the message successfullRankupPublic?
  publicPrestigeMessage: true # Should we send the message successfullPrestigePublic?
options:
  removePointZero: true # Should we remove the .0 at the end of prices?
  prestigeDisabled: false # Should we disable prestiging?
  prestigeToRank: A # When someone prestiges, what rank should we set them to
  prestigeAtRanks: D # At what rank can someone prestige? (can be multiple ranks, eg if you write D,E)
  prestigeRankMultiplier: 1.5 # Multiply the rankup prices by this when someone prestiges (set to 1 to disable) (do not set to less than 1)
  prestigeChangeRank: true # You should leave this at true
runCommands: {} # These are some examples of what you can do with runCommands. They are commented out so they don't run. Remove the {} when you want to add a command
#- CONSOLE:RANKUP:say console rankup (this will make the console run this command when a player ranks up)
#- PLAYER:RANKUP:say player rankup (this will make the player run this command when that player ranks up)
#- CONSOLE:PRESTIGE:say console prestige (this will make the console run this command when a player prestiges)
#- PLAYER:PRESTIGE:say player prestige (this will make the player run this command when that player prestiges)
#- PLAYER:B:say I ranked up to rank B (this will make the player run this command when they rank up to rank B)
#- CONSOLE:P2:say %PLAYER% prestiged to P2 (this will make the console run this command when a player prestiges to P2)
gui: # How should the GUI be made 
  size: 9 # The size of the GUI. Must be a multiple of nine.
  'yes': # Options specifying the 'yes i want to rankup' block
    material: EMERALD_BLOCK
    lore: ' '
    index: 0-3
    name: '&a&lRankup'
  'no': # Options specifying the 'no i don't want to rankup - cancel' block
    material: REDSTONE_BLOCK
    lore: ' '
    index: 5-8
    name: '&cCancel'
  fill: # What block we should use to fill the spaces in the GUI
    name: ' '
    lore: ' '
    material: STAINED_GLASS_PANE:15
  name: '&cRankup to %RANK% for %AMOUNT%' # The name of the GUI at the top (cannot be longer than 32 characters or an error will be thrown)
placeholders:
  currentRankCostFormat: '0.00'
  nextRankCostFormat: '0.00'
  useShortening: true # Whether we should shorten rank prices (eg turn $1000 into $1k)
  shortened:
  - k
  - M
  - B
  - T
  percentDoneFormat: '#.##'
  percentLeftFormat: '#.##'
  allowNegativePercent: false
  highestRank: 'None' # What should be used as a placeholder for ranks above the highest rank
